#!/usr/bin/env python3
"""
Robust YOLO dataset filter: remove honey (class 2) and nectar (class 4),
remap remaining classes to 0–4, and guarantee every image has a label file.

Usage:
    python filter_labels.py <input_dataset_root> <output_dataset_root>

The output dataset will have the same layout as the input,
with labels filtered and image files copied verbatim.

Generated by DeepSeek.
"""

import sys
import shutil
from pathlib import Path
from collections import Counter

# Class mapping: old 7‑class ID → new 5‑class ID
OLD_TO_NEW = {
    0: 0,   # capped -> 0
    1: 1,   # eggs   -> 1
    3: 2,   # larves -> 2
    5: 3,   # other  -> 3
    6: 4,   # pollen -> 4
}
REMOVE = {2, 4}   # honey, nectar
CLASS_NAMES = ['capped', 'eggs', 'larves', 'other', 'pollen']

# Recognized image extensions (adjust as needed)
IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.bmp', '.tif', '.tiff'}


def filter_labels_from_source(src_label_path, dst_label_path):
    """Read source label, remove honey/nectar, remap, write to dst.
       Always writes a file (may be empty).
       Returns (kept_count, removed_count)."""
    removed = 0
    new_lines = []
    if src_label_path and src_label_path.is_file():
        with open(src_label_path, 'r') as f:
            lines = f.readlines()
        for line in lines:
            parts = line.strip().split()
            if not parts:
                continue
            try:
                cls_id = int(parts[0])
            except ValueError:
                continue
            if cls_id in REMOVE:
                removed += 1
                continue
            new_id = OLD_TO_NEW.get(cls_id)
            if new_id is None:
                removed += 1
                continue
            parts[0] = str(new_id)
            new_lines.append(' '.join(parts))
    # else: no source label → keep empty

    dst_label_path.parent.mkdir(parents=True, exist_ok=True)
    with open(dst_label_path, 'w') as f:
        f.write('\n'.join(new_lines) + ('\n' if new_lines else ''))
    return len(new_lines), removed


def audit_dataset(root):
    """Print per-split stats for the newly created dataset."""
    print("\n" + "="*60)
    print("  AUDIT OF FILTERED DATASET")
    print("="*60)
    for split in ['train', 'val', 'eval']:
        labels_dir = root / 'labels' / split
        images_dir = root / 'images' / split
        if not labels_dir.is_dir() or not images_dir.is_dir():
            print(f"  {split}: skipped (missing images/ or labels/)")
            continue

        # Count images (any image extension)
        image_files = [f for f in images_dir.iterdir()
                       if f.suffix.lower() in IMAGE_EXTENSIONS]
        num_images = len(image_files)

        label_files = sorted(labels_dir.rglob('*.txt'))
        num_labels = len(label_files)

        class_counter = Counter()
        density = Counter()
        total_annot = 0

        for lf in label_files:
            with open(lf, 'r') as f:
                lines = f.readlines()
            tile_annot = 0
            for line in lines:
                parts = line.strip().split()
                if not parts:
                    continue
                try:
                    cls_id = int(parts[0])
                    if 0 <= cls_id < len(CLASS_NAMES):
                        class_counter[cls_id] += 1
                        tile_annot += 1
                except ValueError:
                    continue
            density[tile_annot] += 1
            total_annot += tile_annot

        print(f"\n{'─'*60}")
        print(f"  SPLIT: {split.upper()}")
        print(f"{'─'*60}")
        print(f"  Images found                : {num_images}")
        print(f"  Label files                 : {num_labels}")
        print(f"  Total annotations           : {total_annot}")
        if num_images != num_labels:
            print(f"  ⚠ WARNING: Image/label count mismatch!")

        print(f"  Class distribution:")
        max_cls = max(class_counter.values()) if class_counter else 1
        for cls_id, name in enumerate(CLASS_NAMES):
            cnt = class_counter[cls_id]
            bar = '█' * int(cnt / max_cls * 40) if max_cls else ''
            print(f"    {cls_id} {name:10s} {cnt:6d}  {bar}")

        print(f"\n  ANNOTATION DENSITY (post-filter, top rows)")
        print(f"  {'Annots/tile':<12} {'Tiles'}")
        print(f"  {'-'*22}")
        for annots in sorted(density)[:20]:  # first 20 levels are enough to inspect
            print(f"  {annots:<12} {density[annots]}")
        if len(density) > 20:
            print(f"  ... ({len(density)} unique density values total)")
    print()


def main():
    if len(sys.argv) != 3:
        print("Usage: python filter_labels.py <input_dir> <output_dir>")
        sys.exit(1)

    src_root = Path(sys.argv[1])
    dst_root = Path(sys.argv[2])

    if not src_root.is_dir():
        print(f"Input directory does not exist: {src_root}")
        sys.exit(1)

    # Clean destination
    if dst_root.exists():
        print(f"Removing existing output directory: {dst_root}")
        shutil.rmtree(dst_root)

    # Copy everything except .txt files
    print(f"Copying non-label files from {src_root} to {dst_root} ...")
    shutil.copytree(src_root, dst_root, ignore=shutil.ignore_patterns('*.txt'))

    # Process each split: iterate over images, generate corresponding filtered label
    splits = ['train', 'val', 'eval']
    total_kept = 0
    total_removed = 0

    for split in splits:
        src_images_dir = src_root / 'images' / split
        src_labels_dir = src_root / 'labels' / split
        dst_labels_dir = dst_root / 'labels' / split

        if not src_images_dir.is_dir():
            print(f"  Warning: no images/{split}/ directory, skipping split.")
            continue

        dst_labels_dir.mkdir(parents=True, exist_ok=True)

        image_files = [f for f in src_images_dir.iterdir()
                       if f.suffix.lower() in IMAGE_EXTENSIONS]
        print(f"Processing {split}: {len(image_files)} images ...")

        for img_path in image_files:
            stem = img_path.stem  # filename without extension
            src_label = src_labels_dir / f"{stem}.txt" if src_labels_dir.is_dir() else None
            dst_label = dst_labels_dir / f"{stem}.txt"

            kept, removed = filter_labels_from_source(
                src_label if (src_label and src_label.is_file()) else None,
                dst_label
            )
            total_kept += kept
            total_removed += removed

    print(f"\nFiltering complete.")
    print(f"Annotations kept: {total_kept}, removed (honey/nectar): {total_removed}")
    print(f"Dataset ready at: {dst_root}")

    # Run audit
    audit_dataset(dst_root)


if __name__ == '__main__':
    main()